server:
  port: 9090
  contextPath: /helloboot
  
spring:
  datasource:
    name: local_mydb
    url: jdbc:mysql://127.0.0.1:3306/my_db
    username: bigboy
    password: Pr0d1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pccw.bigboy.article.dao
